#ifndef RPGSS_VERSION_HPP_INCLUDED
#define RPGSS_VERSION_HPP_INCLUDED

#define RPGSS_VERSION_MAJOR   0
#define RPGSS_VERSION_MINOR   5
#define RPGSS_VERSION_RELEASE 0

#define RPGSS_VERSION "RPGSS 0.4.0"
#define RPGSS_VERSION_NUM (RPGSS_VERSION_MAJOR * 100 * 100 + RPGSS_VERSION_MINOR * 100 + RPGSS_VERSION_RELEASE)

#endif
